apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  labels:
    app: scheduler
spec:
  replicas: {{ .Values.schedulerreplicas }}
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler-service
          image: {{ .Values.global.imageregistry }}/enterprise-platform-scheduler:{{ .Values.schedulerimagetag }}
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.global.kafkaBootstrapServers }}
            - name: JAVA_OPTS
              value: {{ .Values.global.javaOpts }}
            - name: SCHEDULER_CRON_PROCESSING
              value: "0 */5 * * * *"
          resources:
            requests:
              cpu: "100m"
              memory: "96Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 10
            failureThreshold: 24

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: scheduler-service

spec:
  selector:
    app: scheduler

  ports:
    - name: http
      port: 8080
      targetPort: 8080

    - name: management
      port: 8081
      targetPort: 8081

  type: ClusterIP