apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
  labels:
    app: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion-service
          image: chinmaya1/enterprise-platform-ingestion:1.0.1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: platform-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: platform
            - name: DB_SCHEMA
              value: ingestion_schema
            - name: DB_USER
              value: platform
            - name: DB_PASSWORD
              value: platform
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: platform-kafka:9092
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 10
            failureThreshold: 24

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
